$file = FileOpen("maplist.txt", 0)

While 1
    $map = FileReadLine($file)
    If @error = -1 Then ExitLoop
FileDelete("H:\spiele\Quake\mparch\fitz*")
Run("fitzquake085.exe -game mparch -width 1024 -height 768 -bpp 32 -nosound -nolan +deathmatch 1 +map " & $map)
Sleep(7000)
Send("k")
Sleep(1000)
Send("s")
Send("k")
Sleep(800)
Send("s")
Send("k")
Sleep(800)
Send("s")
Send("k")
Sleep(800)
Send("s")
Sleep(800)
Run("taskkill /F /IM fitzquake085.exe")
Sleep(1000)
Run("C:\Program Files\ImageMagick-6.5.4-Q8\convert.exe -format jpeg -quality 75 -strip H:\spiele\Quake\mparch/fitz0000.tga H:\spiele\Quake\mparch/"&$map&"_1.jpg")
Sleep(1500)
Run("C:\Program Files\ImageMagick-6.5.4-Q8\convert.exe -format jpeg -quality 75 -strip H:\spiele\Quake\mparch/fitz0001.tga H:\spiele\Quake\mparch/"&$map&"_2.jpg")
Sleep(1500)
Run("C:\Program Files\ImageMagick-6.5.4-Q8\convert.exe -format jpeg -quality 75 -strip H:\spiele\Quake\mparch/fitz0002.tga H:\spiele\Quake\mparch/"&$map&"_3.jpg")
Sleep(1500)
Run("C:\Program Files\ImageMagick-6.5.4-Q8\convert.exe -format jpeg -quality 75 -strip H:\spiele\Quake\mparch/fitz0003.tga H:\spiele\Quake\mparch/"&$map&"_4.jpg")
Sleep(1500)
FileDelete("H:\spiele\Quake\mparch\fitz*")
sleep(5000)
Wend

FileClose($file)